Auto FP32/QAT Detection
neuralmagic/pytorch-image-models pull request #4
Opened 2021-11-30 18:42 UTC by KSGulin

2021-11-30 20:20 UTC, bfineran requested changes

2021-11-30 20:20 UTC, bfineran commented on train.py
> +    if qat:
can we move this to the base train function so we only need to run this "disabling half precision..." step once?

2021-11-30 23:03 UTC, bfineran approved these changes

2021-12-03 19:02 UTC, rahul-tuli approved these changes

2022-01-11 16:43 UTC, merged